title: Will's Portfolio
logo: /main/Black Modern Personal LinkedIn Banner (8).png
description: >

First Description
<br><br>
Second Description
<br><br>
<a href="https://www.linkedin.com/in/wsoublo/">View My LinkedIn Profile</a>

show_downloads: true
google_analytics: G-6WWPV1GVXN
theme: jekyll-theme-minimal
