title: Will's Portfolio
logo: /main/Black Modern Personal LinkedIn Banner (8).png
description: Showcasing my projects

<a href="https://linkedin.com/in/wsoublo">View My LinkedIN Profile</a>
show_downloads: true
google_analytics: G-6WWPV1GVXN
theme: jekyll-theme-minimal
